export const GitHubEvents = {
    COMMIT_COMMENT: "CommitCommentEvent",
    CREATE: "CreateEvent",
    DELETE: "DeleteEvent",
    FORK: "ForkEvent",
    GOLLUM: "GollumEvent",
    ISSUE_COMMENT: "IssueCommentEvent",
    ISSUE: "IssuesEvent",
    MEMBER: "MemberEvent",
    PUBLIC: "PublicEvent",
    PULL_REQUEST: "PullRequestEvent",
    PULL_REQUEST_REVIEW: "PullRequestReviewEvent",
    PULL_REQUEST_REVIEW_COMMENT: "PullRequestReviewCommentEvent",
    PULL_REQUEST_REVIEW_THREAD: "PullRequestReviewThreadEvent",
    PUSH: "PushEvent",
    RELEASE: "ReleaseEvent",
    SPONSORSHIP: "SponsorshipEvent",
    WATCH: "WatchEvent",
};
